[package]
name = "sdkwork-api-image-assembly"
edition.workspace = true
version.workspace = true
description = "Generated API assembly for sdkwork-image application HTTP plane."

[lib]
name = "sdkwork_api_image_assembly"
path = "src/lib.rs"

[dependencies]
axum.workspace = true
tokio.workspace = true
sdkwork_web_bootstrap = { workspace = true }
sdkwork-web-core.workspace = true
sdkwork-database-sqlx.workspace = true
sdkwork-image-generation-host.workspace = true
sdkwork-image-generation-provider-spi.workspace = true
sdkwork-routes-image-app-api.workspace = true
